### ISSUE TITLE
Hard fork to slighly increase amount of PoW

### ISSUE THREAD

**Issue by bitcoin-pow** [bitcoin-pow/BitcoinPoW#44]
Increase the amount of sha256 on each kernel hash calculation. This will allow an i9 to max out at 100% loading with much less utxos, rather than a few million utxos. This increases the cost of hardware resources as they max out faster. This will make a better balance between cost of utxos and cost of computers to mine. The original BTCW can fit one month of network mining on a single computer, this update will change that.

**Comment by Jeans-rgb** [comment]
Instead of having a fixed window of 256 possibilities, it could be interesting to make this window variable and increase the number of possibilities in link with difficulty in steps.

To achieve this, we could use a function applied to the difficulty, for example: window = 2^[LOG4(diff)] with [x] rounded to the nearest lower integer.

So when the difficulty reaches a certain threshold, the window will increase. 
Following the difficulty sequence 1, 4, 16, 64, 256, 1024, 4096, 16384, 65536, 262144, 1048576, etc., 
corresponding to the window sequence: 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, etc.

For example, if the current update occurs with a difficulty of 45, then the window will be 4. The difficulty will quickly increase due to the computers that can handle the change in ratio. It will soon surpass 64 with a corresponding window of 8.

Therefore, with a window of 8, each UTXO has 8 possible iterations. So with approximately 350 million UTXOs used for mining, this gives a hashrate of 350 * 8 = 2800 Mhs. This corresponds to a difficulty of about 391. This means that the network will quickly exceed the difficulty of 256 and therefore stabilize at a window of 16 before the increase in PoT pushes the window to 32 when the difficulty reaches 1024. These 1024 will be reached when approximately 460 million UTXOs are used for mining, etc.

The window of 256 will be reached at difficulty 65536, so when approximately 3665 million UTXOs are used for mining, which should occur in 4.5 to 6 years if all goes well.

Obviously, once a threshold is reached, it is impossible to imagine going back to a lower threshold, making a decrease in the window very unlikely.

The short-term effect should be quite interesting as it should allow small miners with few UTXOs to better utilize their hardware. And it should force large miners with computers full of UTXOs to buy or used new hardware if they want to utilize all their UTXOs. This should result in a better distribution of the hashrate.

In the longer term, the effects of these increases should facilitate the entry of new miners because UTXOs acquired later will be more "profitable" than those acquired earlier. This should also calm the UTXOs market with periods of tranquility and periods of reaction to the increase in the window.

This is a proposal to the BitcoinPow developer to find an acceptable compromise for the entire mining community following the BitcoinPoW fork proposal.

**Comment by bitcoin-pow** [comment]
Thanks for your suggestion, however that would eventually result in BTCW becoming nearly 100% PoW in the future making PoT almost meaningless. The goal is to have mining primarily accomplished using PoT, but the network needs a little push towards PoW so there is more dependency on computer growth in the short term so that greedy mining is not free but actually has a cost. This will allow entry of new miners and keep BTCW as a green environmental coin in the future as well. We do not want to converge into a solution that is basically BTC as you have suggested.

**Comment by Jeans-rgb** [comment]
Thanks for taking the time to consider my proposal. I respectfully disagree because with the increase in ROI to start mining, the hashrate likely won't experience linear growth and will eventually plateau to grow slowly.
Therefore, the window would have stabilized as well for a long time around 256, and maybe never reaching 512.
We'll never know.
